AWSTemplateFormatVersion: "2010-09-09"
Description: sfn-status-notifier

Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'SfnStatusNotifier'
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: DataType
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: DataType
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: FindByDataType
          KeySchema:
            - AttributeName: DataType
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST